### ISSUE TITLE
how to convert a BLOB object (audio) in a normal audio like .mp3 or .wav for update to database

### ISSUE THREAD

**Issue by EmmanuelSkapple** [hackingbeauty/react-mic#10]
I want update An audio recorded with the microphone to my firebase database , but I get an BLOB object and I take the url like this blob:http://localhost:3000/b890eafb-2265-458e-a9d8-84b81657d7fb but if I want play this audio in other computer not heard.

And the only thing I can think of is to convert it to .mp3 or .wav and upload it

**Comment by hackingbeauty** [comment]
@EmmanuelSkapple, react-mic returns an object when you stop recording.  The object looks like this:
```
 {
  blob: Blob,
  startTime: 1498513001921,
  stopTime: 1498513004938, 
  blobURL: "blob:http://localhost:3000/fa541b07-56ba-4797-8bb8-593d7fb7141e"
}
```

Do you notice the key in this object titled "blob"?  That is the binary representation of the audio file you can upload to Firebase.
