### ISSUE TITLE
Pause and Resume

### ISSUE THREAD

**Issue by Khachatour** [hackingbeauty/react-mic#14]
Hey there!! I am know deeply into your code, and trying to find possible ways to pause and resume recording. Do you have any suggestions on how I can achieve this ?

**Comment by hackingbeauty** [comment]
<ReactMic /> takes a "record" prop.  When the record prop is set to true, the recording begins.  When the record prop is set to false, the recording stops.  

```
<ReactMic
  record={true || false}
/>
```

**Comment by Khachatour** [comment]
@hackingbeauty the thing is that it stops, not paused, I did some refactoring and added, pause and resume in reactmic.js and in MicrophoneRecorder also, and managed to get context canvas and audio player pause and resume. You can't just pause with setting record props to false, it stops recording not pausing :)

**Comment by hackingbeauty** [comment]
Hi Khachatour, can you submit a PR which include your changes?  I'd love to see them.  Thank you!

**Comment by Khachatour** [comment]
Yes of course, I can do that today by evening okay ?

**Comment by hackingbeauty** [comment]
No rush!! :)

**Comment by dprabu17** [comment]
> Yes of course, I can do that today by evening okay ?

@Khachatour  Please share your suggestions on how to do pause/resume recording?
