### ISSUE TITLE
Warning: Accessing PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by PEM--** [hackingbeauty/react-mic#15]
PropTypes should be accessed via [`prop-types`](https://www.npmjs.com/package/prop-types)

PS: Thanks for this package 👍

**Comment by hackingbeauty** [comment]
Thanks for the heads up, updated and published to v7.0.4.  Please let me know if you're still having trouble!

**Comment by PEM--** [comment]
@hackingbeauty Unfortunately, despite that you've imported `prop-types`, `ReactMic` was still using thus from `React`. #17 fixes it.
