### ISSUE TITLE
Multiple Record rows in One page

### ISSUE THREAD

**Issue by thnhat51202574** [hackingbeauty/react-mic#18]
I have add react-mic to my own project. But I have a issue, I want to add multiple record in one web page. But onStop event only is called one, and there is only one BLOB file is created if I try recording at any Mic record in own page. Please help, thank alot.

**Comment by hackingbeauty** [comment]
I'd have to rewrite the logic and I don't have the time to do that right now.  But if you create a Pull Request, I'd be happy to look at it and potentially merge it into the package.

**Comment by AndrejStarusev** [comment]
@thnhat51202574, Have you solved this issue?

**Comment by thnhat51202574** [comment]
@AndrejStarusev Yes, I solved it. But I still had some issues. I'll create a Pull request after done all.

**Comment by hackingbeauty** [comment]
@thnhat51202574 Will you be submitting a PR soon?

**Comment by AndrejStarusev** [comment]
It works for me if ReactMic component is not mounted until you are starting record.

```
startRecording() {
        this.setState({ record: true,  isMicOnScene: true }}
}
. . .
{ this.state.isMicOnScene && <ReactMic record={this.state.record} />}
```
