### ISSUE TITLE
Not aborting?

### ISSUE THREAD

**Issue by justinhessdev** [hackingbeauty/react-mic#19]
<img width="77" alt="screen shot 2017-08-18 at 3 23 36 pm" src="https://user-images.githubusercontent.com/7797010/29474361-614e2b66-8429-11e7-9e68-196779e03fa4.png">

As pictured above, the recording icon appears active even after I stop listening.
This is a confusing user experience.

Is it possible the recognition was not properly aborted on your end?
Or can I resolve this on my end?

**Comment by hackingbeauty** [comment]
I believe this is how audio recording works in Chrome.  If you approve access to the microphone and record audio, the recording icon in the tab remains a red dot.

I don't know how to change this.

**Comment by justinhessdev** [comment]
If you look at other web audio packages such as `react-speech-recognition` The red dot goes away once the audio is complete.  Here, the red dot never goes away and is a bit misleading / confusing

I think once the component unmounts or onStop you do something like recognition.abort() and that removes the red dot. 

Package:
`npm install --save react-speech-recognition`

**Comment by hackingbeauty** [comment]
I don't believe this can be done.

I looked at the code for the ``` react-speech-recognition``` npm package and it uses the [SpeechRecognition API](https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition).

When you use ```react-mic``` to record audio, it uses the [MediaRecorder API](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder).

There's no way to remove the red dot when stopping a recording.  If you'd like to experiment yourself, you can edit line 86 of the file ```src/libs/MicrophoneRecorder.js```.

Great suggestion on improving the UI, but I believe this is just how audio recording in Chrome works!
