### ISSUE TITLE
iOS 11 now supports Media Capture API, but react-mic isn't working

### ISSUE THREAD

**Issue by tony-krnl** [hackingbeauty/react-mic#20]
After recording is stopped, the recorded blob size is zero.

**Comment by hackingbeauty** [comment]
Thank you for notifying me!  I will adjust the package shortly and notify you.  Again, thanks for the heads up!

**Comment by hackingbeauty** [comment]
Hey I don't know how to record microphone input on Safari 11.  With Chrome and Firefox, you use the ```MediaRecorder``` API, but that doesn't appear to be available on Safari 11 (iOS + desktop).

Do you know how I can do this for Safari?

**Comment by tony-krnl** [comment]
The information from Apple isn't very helpful - see [here](https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Safari_11_0/Safari_11_0.html). They just claim to support the Media Capture API. And using react-mic, I *do* get prompted for permission, and the browser indicates that the microphone is active, but I'm guessing there's a quirk somewhere in their implementation since the recorded blob is empty.

**Comment by hackingbeauty** [comment]
There is no Media Recorder API in Safari yet.  That is the API used to record audio in the browser.
I can provide an error message for Safari users if they try to record audio from their microphone.

But I don't think we can get this to work in Safari yet.

**Comment by tony-krnl** [comment]
It's only in iOS 11, but it's there.

**Comment by tony-krnl** [comment]
See [this thread](https://github.com/muaz-khan/RecordRTC/issues/324) for a link to a working example.

**Comment by tony-krnl** [comment]
And here's the source for the example (example 3):
https://github.com/GersonRosales/Record-Audios-and-Videos-with-getUserMedia

**Comment by hackingbeauty** [comment]
React-Mic uses the MediaRecorder API to record audio.  Safari doesn't support that API.  So I'm not sure how to get this working in Safari.

**Comment by amitchell89** [comment]
So I'm running into this issue now. So this just doesn't work on safari? is there any plan to try and fix this?

**Comment by octavn** [comment]
This [bug report](https://bugs.webkit.org/show_bug.cgi?id=85851) on bugs.webkit.org tracks the MediaRecorder implementation in WebKit and thus Safari. 

I encourage everyone to show their interest and [add a comment](https://bugs.webkit.org/show_bug.cgi?id=85851) describing how a MediaRecorder implementation would help their project/development. Creating an account takes a second.

Chrome [implemented MediaRecorder in Jan 2016](https://developers.google.com/web/updates/2016/01/mediarecorder), by that time the feature request had gathered [2800+ starts on bugs.chromium.org](https://bugs.chromium.org/p/chromium/issues/detail?id=113676).

**Comment by pincheira** [comment]
Yes, only way to convince them is to add your comment as @octavn says.

Here's the link to [create your account](https://bugs.webkit.org/createaccount.cgi) only with your email address.

After confirming your email and filling in your name, you can now add your comment to [MediaStream API: support MediaStreamRecorder implementation](https://bugs.webkit.org/show_bug.cgi?id=85851). 🎉💪🏻
