### ISSUE TITLE
Detect when to stop recording

### ISSUE THREAD

**Issue by hboylan** [hackingbeauty/react-mic#21]
Is it possible with this library (or would you know how) to stop recording audio after detecting when a user has stopped speaking?

Similar to popular speech recognition integrations (Alexa, Siri, Google).

**Comment by hackingbeauty** [comment]
Yes, I'm sure it is :)

**Comment by hboylan** [comment]
Haha. Well it looks like this library's `onStop()` method must be bound to some user event.

I suppose it would require integrating something like [this](https://github.com/otalk/hark) library to automatically detect when to stop.

**Comment by hackingbeauty** [comment]
Can you take a stab at it and issue a PR?  Happy to get you set up.  

A prop should be passed to the component indicating that recording should stop when user is no longer speaking.  Otherwise, the component displays default behavior.

**Comment by hboylan** [comment]
Possibly. Still researching what type of behavior is ideal for my use case (speech recognition).

[SpeechRecognition](https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition) would work for a client-side implementation, but only works in Chrome/Opera right now.

This library would be ideal for server-side speech recognition using something like [Dialogflow](https://dialogflow.com).

**Comment by Ibrvheem** [comment]
Hello! @hboylan Hope you are good. 
Just curious if you found a way. I am trying to implement something similar. 
Thanks!

**Comment by Arhath** [comment]
Hello Did anyone found a way to do it??
