### ISSUE TITLE
How to Obtain the actual speech blob file?

### ISSUE THREAD

**Issue by daas-ankur-shukla** [hackingbeauty/react-mic#29]
I want to send the speech input to Google/Micrsoft API for speech to text conversion. Any help regarding how to get the actual blob/audio file to send to the API end point would be appreciated. I hope I am not asking a trivia (I am new to React).

**Comment by hackingbeauty** [comment]
@daas-ankur-shukla,

You need to pass a callback to the ```onStop``` prop of React-Mic.  Like this:

```
onStopCallback(recordedBlob) {
  /* Do something with recordedBlob here */
}

<ReactMic
  record={this.state.record}
  onStop={this.onStopCallback} />
```
The callback will receive one argument when the user stops recording which is the recorded BLOB.  This BLOB is what you send to your API endpoint for processing.

**Comment by daas-ankur-shukla** [comment]
@trops hi. with whatever little experience i have had with this component. I got the data in the blob as mentioned by @hackingbeauty in his comment. My issue however was about the format in which the blob was generated. It will always be generated in the default format.

**Comment by trops** [comment]
I havent been able to. I am uploading to my endpoint then my endpoint handles the upload to S3, I think that is the issue. So I am still left with corrupt audio files for whatever reason. Really wish there was a straightforward way of saving the files.

**Comment by akigmm** [comment]
@hackingbeauty When we call the API from index.js the onStop prop has to be added inside the render which is giving the error of cannot change the transition because of which the callback is never happening

**Comment by free2580** [comment]
Any Idea why the sound wave stroke line only works the first recording? Still records, but I have to refresh to actually see the sound wave again. Any advice?

**Comment by hackingbeauty** [comment]
@free2580 this problem was already fixed.  Please update your version of React-Mic to the latest version, and let me know if everything works for you as expected.

**Comment by free2580** [comment]
@hackingbeauty I have latest version (react-mic@12.4.0), no change

**Comment by hackingbeauty** [comment]
@free2580 good catch.  Can you upgrade to react-mic@12.4.1 and verify that it works for you?  I just pushed a patch.

**Comment by Alina03** [comment]
@hackingbeauty How can we send the recorded audio to the flask api and then store it to mysql?

**Comment by hackingbeauty** [comment]
@Alina03 Yes, you can do whatever you want with the audio.

**Comment by Alina03** [comment]
My question was how can we send the recorded audio to the flask api?
