### ISSUE TITLE
Generate Result as .wav

### ISSUE THREAD

**Issue by AbdulHakimRithm** [hackingbeauty/react-mic#30]
Hey. So i have a need to save the audio as a .wav file to the back end. But react-mic is only returning as a .webm format only.

I tried passing the mime type in the props like this :
`<ReactMic mimeType="audio/wav">`

But it doesn't seem to work. When i hit the returned blobURL, and downloaded the file, the file is in .wav, but when i right click it and open it's audio properties, it says the container is WebM and codec is Opus. audio/webm codec=opus, are all default prop values. So how can i get the result as a real .wav file?

**Comment by daas-ankur-shukla** [comment]
@AbdulHakimRithm i also need the same thing. @hackingbeauty if you could shed some light on this, it will be great

**Comment by daas-ankur-shukla** [comment]
hey @AbdulHakimRithm i just tried doing what u had done and it is working for me. may there has been a patch.

**Comment by daas-ankur-shukla** [comment]
@hackingbeauty can we change the audioBitsPerSecond?
