### ISSUE TITLE
How to obtain real time data??

### ISSUE THREAD

**Issue by adarshks** [hackingbeauty/react-mic#32]
I have tried to use the onData function , but the callback is not firing so i am not able to get the real time data. can anyone help?

onData(recordedBlob) {
        console.log('chunk of real-time data is: ', recordedBlob);
    }

<ReactMic
                                    record={this.state.record}
                                    className="sound-wave"
                                    onData={this.onData}
                                    onStop={this.onStop}
                                    strokeColor="#000000"
                                    backgroundColor="#c3c2bf" />

**Comment by pegetive** [comment]
I also have this problem for onData(). Nothing happens by assigning a function to it.

**Comment by pavestru** [comment]
Not sure what happened to this project. onData was clearly merged in this [pull request](https://github.com/hackingbeauty/react-mic/pull/31) but it's currently not there. It seems the current contributor reset the history to [this commit](https://github.com/hackingbeauty/react-mic/commit/f2e7f421b09f0fd96e950ddaa706eb78f0b66969) and continued from then on...

Anyway, to use onData, use [this fork](https://github.com/pavestru/react-mic/tree/add-ondataavailable-callback) or create your own.

**Comment by hackingbeauty** [comment]
```onData``` has been added back!  Didn't know the community needed that feature.
