### ISSUE TITLE
how can i change the type to "audio/wav" ? 

### ISSUE THREAD

**Issue by ELI7VH** [hackingbeauty/react-mic#37]
I looked in the source and it said something about `options` but I can't really figure out what to put.

would also be nice to be able to assign a bitrate, as the quality is a bit low for my needs.

**Comment by alexWang007** [comment]
I have also encountered this problem

**Comment by JonMorales22** [comment]
I also ran into this issue, but I'm not sure if react-mic can record audio in another format besides the default .webm format.

So right now I'm just using react-mic to record the audio and then using another program called ffmpeg to convert the audio into the format I need.

**Comment by hackingbeauty** [comment]
Hi everyone, React-Mic can't save files as audio/wav.  Right now, React-Mic uses the MediaRecorder API which saves audio as audio/webm.

We would need to add much more logic to this very light-weight component to be able to save audio files as audio/wav.
