### ISSUE TITLE
Visualization do not work first time 

### ISSUE THREAD

**Issue by viveknimkarde** [hackingbeauty/react-mic#39]
https://hackingbeauty.github.io/react-mic/
Check out demo app . Visualization dont work first time

**Comment by viveknimkarde** [comment]
This issue started showing up in chrome recently

**Comment by hackingbeauty** [comment]
Hey good catch, I'm going to patch that this weekend.  Please stand by.

**Comment by hackingbeauty** [comment]
Hey, I just published react-mic version 4.0.0 which fixes this issue.  Thank you notifying me about this issue! :D
