### ISSUE TITLE
Window is not defined

### ISSUE THREAD

**Issue by dovancao** [hackingbeauty/react-mic#43]
Hi there,
Thank you for awesome code
When i try it, i got this problem. Anyone can help?
![screenshot_1](https://user-images.githubusercontent.com/36324165/43830542-b7b4f5b0-9b2b-11e8-9eb0-419ed242ddf6.png)

**Comment by hackingbeauty** [comment]
The window object only exists in the browser.  Are you trying to run React-Mic in a different environment?

**Comment by omarefg** [comment]
Do you have any plan on supporting SSR?

**Comment by hackingbeauty** [comment]
@omarefg I'm getting more requests for this.  Can you join the public Slack channel to discuss?

https://hackingbeauty-slack-invite.herokuapp.com

**Comment by pranshu1995** [comment]
I am trying to use this library in NextJS, but getting the error

`ReferenceError: window is not defined`

Is there any support for SSR yet?
