### ISSUE TITLE
onSave callback function  invalid

### ISSUE THREAD

**Issue by manwuyu** [hackingbeauty/react-mic#44]
I found  onStart and onStop function work well， but  onSave  function  not work

version : "react-mic": "^11.0.0"

**Comment by manwuyu** [comment]
12.0.0   also  not work

**Comment by hackingbeauty** [comment]
Sorry about that.  Can you upgrade to 12.1.0 and let me know?  Should be fixed now.

**Comment by manwuyu** [comment]
3Q，12.1.0 is OK
