### ISSUE TITLE
How to modify  Blob Size ？

### ISSUE THREAD

**Issue by manwuyu** [hackingbeauty/react-mic#45]
"react-mic": "^11.0.0",

<ReactMic
                                          record={record}
                                          save={save}
                                          className="sound-wave"
                                          onSave={this.onSave}
                                          onStart={this.onStart}
                                          onStop={this.onStop}
                                          visualSetting="sinewave"
                                          audioBitsPerSecond= {10}
                                          mimeType= {'audio/amr-wb'}
                                          strokeColor="#000000"
                                          backgroundColor="#FF4081" />
                                    </div>

audioBitsPerSecond  change  but  Blob Size  No change

**Comment by hackingbeauty** [comment]
I don't know ```audioBitsPerSecond``` is being passed into the MediaRecorder API constructor.

```
const mediaOptions = { audioBitsPerSeconds: 10 }
new MediaRecorder(str, mediaOptions)
```

What's the expected behavior when you change audioBitsPerSecond?

**Comment by manwuyu** [comment]
Making Blob Size smaller，I need  record one minute voice file size less than 100K， mimeType:  audio/amr-wb

**Comment by hackingbeauty** [comment]
@manwuyu, I'm limited by what the MediaRecorder API can do.  The ```audio/amr-wb``` MimeType is not supported by the MediaRecorder API.
