### ISSUE TITLE
Red dot visible after setting record =false

### ISSUE THREAD

**Issue by gautamrh** [hackingbeauty/react-mic#47]
Hi
How do I get rid of the red dot when I move to the next page. Any specific method i need to call?

**Comment by hackingbeauty** [comment]
Please update your version of ```React-Mic``` to the latest version (12.2.0)

**Comment by gautamrh** [comment]
Hi 
Thanks for your response. I have already updated to the latest version but the issue is still present. Do i need to do anything extra when I move to next page? Please help

**Comment by hackingbeauty** [comment]
You need to stop the recording before you move to the next page.  Are you doing that?

The demo app [Voice Record Pro](http://voicerecordpro.com/#/record) shows how the red dot goes away when you stop recording.  It's using React-Mic 12.2.0.

**Comment by gautamrh** [comment]
Hi 

Thanks, it worked. 

Regards,
Gautam
