### ISSUE TITLE
Record bool doesn't stop the component from recording when using redux to store the value 

### ISSUE THREAD

**Issue by ankithkonda** [hackingbeauty/react-mic#50]
Hi, 

I use redux to store the bool to start and stop the recording, and when I call the action to update the redux "record" variable to false, the render function sees the change, however, the recording still continues. However, if I use the component's state, it works as expected.

**Comment by hackingbeauty** [comment]
I use Redux to start and stop recording.  It works for me so you must have
a bug somewhere.

**Comment by ankithkonda** [comment]
No worries, I'll have another look. Thank you
