### ISSUE TITLE
Why circular frequency visualizer not in master?  #26

### ISSUE THREAD

**Issue by andriyor** [hackingbeauty/react-mic#53]

**Comment by hackingbeauty** [comment]
Can you give me some context?  What is the circular frequency visualizer?

**Comment by andriyor** [comment]
#26

**Comment by hackingbeauty** [comment]
OK, I added the circular frequency visualizer.  Can you verify that it works for you?

Sorry this wasn't added earlier!  :D

**Comment by andriyor** [comment]
I verified and everything works pretty good, thank you.
