### ISSUE TITLE
when I use it at the second time, The sound wave  animation was freezing.

### ISSUE THREAD

**Issue by ryanyu104** [hackingbeauty/react-mic#55]
version: 12.3.0

At the first time, When I use react-mic, the animation is ok.
After that, I tried to record at the second time, the animation has frozen.
Same as the [demo](https://hackingbeauty.github.io/react-mic/)

**Comment by WaVEV** [comment]
Hi, I have the same problem.
I have a kind of fix, I don't know if the fix is in the right way. 
You can see my fork of this reporsitory
https://github.com/WaVEV/react-mic

**Comment by bgibso4** [comment]
I am having the same problem. Can you explain what you mean by kind of a fix?

**Comment by hackingbeauty** [comment]
@WaVEV the changes in your repo were excellent, thank you for sharing!

The wave animation problem has been fixed in version 12.4.0 of React-Mic.  Please test and let me know if anyone still has issues!

**Comment by hackingbeauty** [comment]
@arnaudambro I forgot to update the demo.  Please try again.  You may need to access the demo in incognito mode on Chrome due to caching.

Please let me know.  Thank you!
