### ISSUE TITLE
Uncaught Error: The error you provided does not contain a stack trace.

### ISSUE THREAD

**Issue by alijch68** [hackingbeauty/react-mic#59]
when i upload project on remote server this error occures.
but it works correctly on my local.

`Uncaught Error: The error you provided does not contain a stack trace.
    at B (index.js:1582)
    at G (index.js:1899)
    at index.js:1914
    at index.js:1933
    at index.js:1414
B @ index.js:1582
G @ index.js:1899
(anonymous) @ index.js:1914
(anonymous) @ index.js:1933
(anonymous) @ index.js:1414
record:1 Uncaught (in promise) DOMException`

**Comment by derek-adair** [comment]
Also getting this on my remote IDE.

**Comment by derek-adair** [comment]
99% sure this is because i didn't have https enabled.  Have not had time to set up on an ssl enabled.

stay tuned!

**Comment by derek-adair** [comment]
was it HTTPS for u ali?

**Comment by alijch68** [comment]
> was it HTTPS for u ali?

yes, it works correctly on localhost and https
