### ISSUE TITLE
How to upload created blob file to S3?

### ISSUE THREAD

**Issue by sujitsagar** [hackingbeauty/react-mic#63]
Preferably using AWS Amplify Storage class.

One can upload other files using following code.
```
Storage.put('test.txt', 'Hello')
    .then (result => console.log(result))
    .catch(err => console.log(err));
```

**Comment by pejmanjohn** [comment]
Was stuck on same point and learned that you can create a File out of a Blob like so:
`const file = new File([blob], "filename.webm");`

In this project I found I had to pass the inner blob to get to the actual data ("recordedBlob.blob")
