### ISSUE TITLE
Multiple ReactMic in the same page. 

### ISSUE THREAD

**Issue by josuevalrob** [hackingbeauty/react-mic#73]
I have a tab component with one ReactMic per tab. 
If I start recording in one mic, it works, but the data goes to another component... it's weird

You can check it up [here](https://josuevalrob.github.io/jeval-web/record/5d86547d7fa62e0017830f2e) 
User: someone@test.com pass: 123

The party is on [Talking.js](https://github.com/josuevalrob/jeval-web/blob/master/src/components/recordings/Talking.js) file.

Maybe the problem is in the onStop props of the ReactMic. 

I dont know how to handle this.. any clue?

**Comment by hackingbeauty** [comment]
Hi @josuevalrob, your UI is really confusing so I couldn't replicate the problem; however, React-Mic is not designed to run in multiple tabs at the same time.

You have a specialized use case which requires further investigation and tweaking.

**Comment by josuevalrob** [comment]
I just add a condition inside the tab before rendering the component... 

I hope this so complicated app could help anyone. bye!
