### ISSUE TITLE
Add TypeScript types

### ISSUE THREAD

**Issue by mikaello** [hackingbeauty/react-mic#81]
It would be nice if this module could have associated TypeScript-types in _DefinitelyTyped_. Info on how to create such a type package is [documented in their repo](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package).

Here is what I have created so far, if someone wants to build off this:

```typescript
declare module 'react-mic' {
  import * as React from 'react';

  export default class ReactMic extends React.PureComponent<ReactMicProps> {}

  export interface ReactMicProps {
    /** Set to true to begin recording */
    record?: boolean;

    /** Available in React-Mic-Plus upgrade only */
    pause?: boolean;

    visualSetting?: 'sinewave' | 'frequencyBars';

    className?: string;

    /** Callback that is executed when audio stops recording */
    onStop?: (recordedData: Blob) => void;

    /** Callback that is executed when chunk of audio is available */
    onData?: (recordedData: Blob) => void;

    /** Sound wave color */
    strokeColor?: string;

    /** Background color */
    backgroundColor?: string;
  }
}
```

**Comment by mikaello** [comment]
Added pull-request to _DefinitelyTyped_ now: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40845

**Comment by mikaello** [comment]
It is now merged into DefinitelyTyped

**Comment by jigarcognino** [comment]
how can i use it with vite.config.ts?

[vite]: Rollup failed to resolve import "react-mic" from "src/Input.tsx".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`

**Comment by mikaello** [comment]
I'm sorry, I got no experience with Vite, and haven't used this module for years, so I can't help you out here.
