### ISSUE TITLE
Mediarecorder constructor arguments

### ISSUE THREAD

**Issue by prizos** [hackingbeauty/react-mic#9]
Would be good if we could pass constructor arguments back to MediaRecorder ? Mostly to set the encoding format and bitrate etc. Looking at the code there isn't a way currently ?

**Comment by hackingbeauty** [comment]
Hi @prizos, you can't do that at the moment; however, the code can easily be adjusted.

Would love to hear what functionality you need and any other suggestions you may have.  PRs welcome!
